version: '3.7'

services:
  db:
    image: nouchka/sqlite3:latest
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    restart: always
    volumes:
      - .:/b2e
    ports:
      - "8000:8000"
    depends_on:
      - db