# Generated by Django 2.2.5 on 2020-01-10 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='kpi_detail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_key', models.TextField()),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('expiry_days', models.IntegerField()),
            ],
            options={
                'unique_together': {('short_key',)},
            },
        ),
    ]
