# Generated by Django 2.2.5 on 2020-01-10 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='kpi_detail',
            new_name='store_tinyurl',
        ),
    ]
