# Generated by Django 2.2.5 on 2020-01-10 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20200110_2255'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='store_tinyurl',
            name='id',
        ),
        migrations.AddField(
            model_name='store_tinyurl',
            name='url',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='store_tinyurl',
            name='short_key',
            field=models.CharField(editable=False, max_length=50, primary_key=True, serialize=False),
        ),
    ]
