# Generated by Django 2.2.5 on 2020-01-10 17:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0004_auto_20200111_0057'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='store_tinyurl',
            name='expiry_days',
        ),
        migrations.AddField(
            model_name='store_tinyurl',
            name='creator',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
