# Generated by Django 2.2.5 on 2020-01-10 17:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20200111_0121'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='store_tinyurl',
            name='creator',
        ),
    ]
