# Generated by Django 2.2.5 on 2020-01-11 01:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0007_remove_store_tinyurl_creator'),
    ]

    operations = [
        migrations.AddField(
            model_name='store_tinyurl',
            name='creator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='store_tinyurl',
            name='iskeepforever',
            field=models.IntegerField(default=0),
        ),
    ]
